/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import model.Atendimento;
import model.PessoaFisica;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Will
 */
public class BuscarAtendimento extends javax.swing.JInternalFrame {

 String codAtendimento;  
 String tipoCod;

    public JRadioButton getRbFuncionario() {
        return rbFuncionario;
    }

    public void setRbFuncionario(JRadioButton rbFuncionario) {
        this.rbFuncionario = rbFuncionario;
    }

 //

    public void setTipoCod(String tipoCod) {
        this.tipoCod = tipoCod;
    }

  
  public String getTipoCod() {
        return tipoCod;
    }
 //
    
    public BuscarAtendimento() {
        initComponents();
        
        //
        setLocation(300, 20);
        //
    }

    public String getCodAtendimento() {
        return codAtendimento;
    }

    public JButton getbEncerrarAtend() {
        return bEncerrarAtend;
    }

    public JButton getbPesquisarAtend() {
        return bPesquisarAtend;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JTable getMostraAtend() {
        return mostraAtend;
    }

    public JRadioButton getRbAtendimento() {
        return rbAtendimento;
    }

    public JRadioButton getRbConcluido() {
        return rbConcluido;
    }

    public JRadioButton getRbHoje() {
        return rbHoje;
    }

    public JRadioButton getRbPendente() {
        return rbPendente;
    }

    public JRadioButton getRbReclamacao() {
        return rbReclamacao;
    }

    public JRadioButton getRbSugestao() {
        return rbSugestao;
    }

    public JRadioButton getRbTodosTipoAt() {
        return rbTodosTipoAt;
    }

    public JRadioButton getRbTodosTipoSts() {
        return rbTodosTipoSts;
    }

    public JRadioButton getRbUltimaSem() {
        return rbUltimaSem;
    }

    public JRadioButton getRbUltimoMes() {
        return rbUltimoMes;
    }

    public JRadioButton getRbultimoAno() {
        return rbultimoAno;
    }

    public JTextArea getTaSugRec() {
        return taSugRec;
    }

    public JTextField getTfCodAtend() {
        return tfCodAtend;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgRec_Sug = new javax.swing.ButtonGroup();
        bgTipoCod = new javax.swing.ButtonGroup();
        bgDataAbert = new javax.swing.ButtonGroup();
        bgStatus = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        bPesquisarAtend = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbHoje = new javax.swing.JRadioButton();
        rbUltimaSem = new javax.swing.JRadioButton();
        rbUltimoMes = new javax.swing.JRadioButton();
        rbultimoAno = new javax.swing.JRadioButton();
        tfCodAtend = new javax.swing.JTextField();
        bEncerrarAtend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostraAtend = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rbPendente = new javax.swing.JRadioButton();
        rbConcluido = new javax.swing.JRadioButton();
        rbTodosTipoSts = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rbReclamacao = new javax.swing.JRadioButton();
        rbSugestao = new javax.swing.JRadioButton();
        rbTodosTipoAt = new javax.swing.JRadioButton();
        rbAtendimento = new javax.swing.JRadioButton();
        rbFuncionario = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taSugRec = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Atendimentos");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Pesquisar Cód:");

        bPesquisarAtend.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        bPesquisarAtend.setText("Pesquisar");
        bPesquisarAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisarAtendActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Data de Abertura:");

        bgDataAbert.add(rbHoje);
        rbHoje.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbHoje.setText("Hoje");

        bgDataAbert.add(rbUltimaSem);
        rbUltimaSem.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbUltimaSem.setText("Na última semana");

        bgDataAbert.add(rbUltimoMes);
        rbUltimoMes.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbUltimoMes.setText("No último mês");

        bgDataAbert.add(rbultimoAno);
        rbultimoAno.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbultimoAno.setText("No último ano");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbUltimoMes)
                            .addComponent(rbHoje))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbUltimaSem)
                            .addComponent(rbultimoAno)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbHoje)
                    .addComponent(rbUltimaSem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbUltimoMes)
                    .addComponent(rbultimoAno)))
        );

        bEncerrarAtend.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        bEncerrarAtend.setText("Encerrar Atendimento");
        bEncerrarAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEncerrarAtendActionPerformed(evt);
            }
        });

        mostraAtend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Atend.", "Cliente", "Cód. Funcionário", "Assunto", "Status", "Data Abertura", "Data Encerramento"
            }
        ));
        jScrollPane1.setViewportView(mostraAtend);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Status:");

        bgStatus.add(rbPendente);
        rbPendente.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbPendente.setText("Pendente");

        bgStatus.add(rbConcluido);
        rbConcluido.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbConcluido.setText("Concluído");

        bgStatus.add(rbTodosTipoSts);
        rbTodosTipoSts.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbTodosTipoSts.setText("Todos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(rbPendente))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbConcluido)
                            .addComponent(rbTodosTipoSts))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPendente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbConcluido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTodosTipoSts))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Tipo:");

        bgRec_Sug.add(rbReclamacao);
        rbReclamacao.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbReclamacao.setText("Reclamação");

        bgRec_Sug.add(rbSugestao);
        rbSugestao.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbSugestao.setText("Sugestão");

        bgRec_Sug.add(rbTodosTipoAt);
        rbTodosTipoAt.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbTodosTipoAt.setText("Todos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbSugestao)
                            .addComponent(rbReclamacao)
                            .addComponent(rbTodosTipoAt))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbReclamacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSugestao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTodosTipoAt)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        bgTipoCod.add(rbAtendimento);
        rbAtendimento.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbAtendimento.setText("Atendimento");
        rbAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAtendimentoActionPerformed(evt);
            }
        });

        bgTipoCod.add(rbFuncionario);
        rbFuncionario.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbFuncionario.setText("Funcionário");

        taSugRec.setColumns(20);
        taSugRec.setRows(5);
        jScrollPane2.setViewportView(taSugRec);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Reclamação/Sugestão");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(bPesquisarAtend)
                        .addGap(26, 26, 26)
                        .addComponent(bEncerrarAtend)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(rbAtendimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(166, 166, 166))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bPesquisarAtend)
                    .addComponent(tfCodAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEncerrarAtend))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAtendimento)
                    .addComponent(rbFuncionario)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPesquisarAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisarAtendActionPerformed
        Atendimento at = new Atendimento();       
        codAtendimento = tfCodAtend.getText();
        ResultSet resultadoAtend;
        
        String tipoAtend = null;
         if(rbFuncionario.isSelected()){
            tipoAtend = "CODFUNC";
        } 
        else if(rbAtendimento.isSelected()){
            tipoAtend = "CODATEN";
        }
        else {
            tipoAtend = "CODATEN";  
        }
        resultadoAtend = at.retornarAtend(codAtendimento, tipoAtend);
        
                   
        if(rbReclamacao.isSelected() && tfCodAtend.getText().isEmpty()){
         resultadoAtend = at.retornarTipoAt("RECLAMACAO");
        }
        if(rbSugestao.isSelected() && tfCodAtend.getText().isEmpty()){
         resultadoAtend = at.retornarTipoAt("SUGESTAO");   
        }
        if(rbTodosTipoAt.isSelected()){
        resultadoAtend = at.retornarAtend(codAtendimento, tipoAtend); 
        }
        //
        if(rbPendente.isSelected() && tfCodAtend.getText().isEmpty()){
        resultadoAtend = at.retornarTipoStatus("Em Atendimento");
        }
        if(rbConcluido.isSelected() && tfCodAtend.getText().isEmpty()){
        resultadoAtend = at.retornarTipoStatus("Concluído");    
        }
              
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) mostraAtend.getModel();
        mostraAtend.setAutoCreateRowSorter(true);
        ((DefaultTableModel) mostraAtend.getModel()).setRowCount(0);
     
        
        try {

            while (resultadoAtend.next()) {

                String codAtend = resultadoAtend.getString("CODATEN");
                String codCliente = resultadoAtend.getString("CODCLIENTE");
                String codFunc = resultadoAtend.getString("CODFUNC");
                String assunto = resultadoAtend.getString("ASSUNTO");
                String status = resultadoAtend.getString("STATUS");
                String sugestao = resultadoAtend.getString("SUGESTAO");
                String reclamacao = resultadoAtend.getString("RECLAMACAO");
                // DATANAINICIO FORMATADA 
                String dia1 = resultadoAtend.getString("DATAINICIO").substring(8,10);
                String mes1 = resultadoAtend.getString("DATAINICIO").substring(5,7);
                String ano1 = resultadoAtend.getString("DATAINICIO").substring(0,4);
                String dataInicio = (dia1+"/"+mes1+"/"+ano1);             
                // DATAFIM FORMATADA 
                String dataFim;
                if((resultadoAtend.getString("DATAFIM") == null)== false){
                String dia2 = resultadoAtend.getString("DATAFIM").substring(8,10);
                String mes2 = resultadoAtend.getString("DATAFIM").substring(5,7);
                String ano2 = resultadoAtend.getString("DATAFIM").substring(0,4); 
                dataFim = (dia2+"/"+mes2+"/"+ano2);  
                } else {
                dataFim = resultadoAtend.getString("DATAFIM");
                }
                modelo.addRow(new String[]{codAtend, codCliente, codFunc, assunto, status, dataInicio, dataFim });                
                if(tfCodAtend.getText() == null || tfCodAtend.getText().isEmpty() || tfCodAtend.equals("")){
                taSugRec.setText(null);
                taSugRec.setText(null);
                } else {
                    if(sugestao == null){
                    taSugRec.setText("Reclamação: "+reclamacao);  
                    } else{
                    taSugRec.setText("Sugestão: "+sugestao);
                    }
                    
                }
            }
            

            at.fechaConexao();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bPesquisarAtendActionPerformed

    private void bEncerrarAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEncerrarAtendActionPerformed
        Atendimento at = new Atendimento();
        codAtendimento = tfCodAtend.getText();
        at.encerrarAt(codAtendimento);
    }//GEN-LAST:event_bEncerrarAtendActionPerformed

    private void rbAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAtendimentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEncerrarAtend;
    private javax.swing.JButton bPesquisarAtend;
    private javax.swing.ButtonGroup bgDataAbert;
    private javax.swing.ButtonGroup bgRec_Sug;
    private javax.swing.ButtonGroup bgStatus;
    private javax.swing.ButtonGroup bgTipoCod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable mostraAtend;
    private javax.swing.JRadioButton rbAtendimento;
    private javax.swing.JRadioButton rbConcluido;
    private javax.swing.JRadioButton rbFuncionario;
    private javax.swing.JRadioButton rbHoje;
    private javax.swing.JRadioButton rbPendente;
    private javax.swing.JRadioButton rbReclamacao;
    private javax.swing.JRadioButton rbSugestao;
    private javax.swing.JRadioButton rbTodosTipoAt;
    private javax.swing.JRadioButton rbTodosTipoSts;
    private javax.swing.JRadioButton rbUltimaSem;
    private javax.swing.JRadioButton rbUltimoMes;
    private javax.swing.JRadioButton rbultimoAno;
    private javax.swing.JTextArea taSugRec;
    private javax.swing.JTextField tfCodAtend;
    // End of variables declaration//GEN-END:variables
}
