//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoVendasWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendaProdutos
    {
        public int Id { get; set; }
        public string Produto { get; set; }
        public double PrecoUnitario { get; set; }
        public string Codigo { get; set; }
        public string Observacao { get; set; }
        public int Quantidade { get; set; }
        public string DataVenda { get; set; }
        public int Clienteid { get; set; }
        public int Tipoid { get; set; }
        public int Unidadeid { get; set; }
        public Nullable<int> Campanhaid { get; set; }
    
        public virtual Campanhas Campanhas { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Tipos Tipos { get; set; }
        public virtual Unidades Unidades { get; set; }
    }
}
